# Generated by Django 5.1.4 on 2025-01-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafield",
            name="data_type",
            field=models.CharField(
                choices=[("T", "Text"), ("N", "Numeric"), ("B", "Boolean")],
                default="T",
                max_length=1,
            ),
        ),
    ]
