# Generated by Django 5.1.4 on 2025-01-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0002_alter_datafield_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionjob",
            name="patient_sex",
            field=models.CharField(
                blank=True,
                choices=[("", "All"), ("M", "Male"), ("F", "Female")],
                default="",
                max_length=1,
            ),
        ),
    ]
